[project]
name = "showcase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django~=5.1.6",
    "django-environ>=0.12.0",
    "django-tws",
]

[tool.uv.sources]
django-tws = { path = "../", editable = true }

